### PR TITLE
Added ms sql support and grouped tbl inputs to db_compute_boxplot

### PR DESCRIPTION
**Pull request by mkirzon**
Our team has many users that constantly need db-based boxplots. I had pulled down this version and modified it to suit our needs but wanted to push it back to the original package. This is my first R package contribution so apologies for whatever part of the process I didn't get!

### CODE REVIEW

**Comment by edgararuiz-zz** [comment]
Hi @mkirzon , thank you so much for this PR! I'll review it in the next few days.

**Comment by mkirzon** [comment]
Hi @edgararuiz ,
Was wondering if you or anyone else on the team could review this PR in the next few weeks? I'm hoping to transition our team to dbplot on our next release internally.

**Comment by edgararuiz-zz** [comment]
Thank you so much @mkirzon

**Comment by edgararuiz-zz** [comment]
I just tested this change against a Teradata and PostgreSQL connections and both worked! Great job!

**Pull request merged**
